project:
  type: website

website:
  title: Isfar Baset
  navbar:
    background: primary
    search: true
    left:
      # - text: "Home"
      #   file: index.qmd
      # - text: "Tutorials"
      #   file: tutorials.qmd
      - text: "DSAN 5000"
        file: 5000-website/index.qmd

      - text: "DSAN 5100"
        file: 5100-website/index.ipynb
      # - text: "Fundamentals"
      #   file: fundamentals.qmd
      # - text: "Reference"
      #   file: reference.qmd

  sidebar:
    # - title: "Tutorials"
    #   style: "docked"
    #   background: light
    #   contents:
    #     - tutorials.qmd
    #     - tutorial-1.qmd
    #     - tutorial-2.qmd

    - title: "DSAN 5000"
      contents:
        - text: Introduction
          file: 5000-website/index.qmd
        # navigation items
        # - text: Introduction
        #   file: 5000-website/index.qmd
        - text: Code
          href: https://github.com/anly501/dsan-5000-project-isfarbaset
        
        - text: Data
          contents: 
            # - text: Github Repo
            text: Code
            href: https://github.com/anly501/dsan-5000-project-isfarbaset
            # - text: Modified Data
            #   file: ../../data/01-modified-data/example.csv

        - text: Data Gathering
          contents:

            - text: Yahoo
              file: 5000-website/data-gathering/yahoo.ipynb

            - text: Rapid API
              file: 5000-website/data-gathering/rapid-api.ipynb

            - text: Cars API
              file: 5000-website/data-gathering/cars-api.ipynb

            - text: News API 
              file: 5000-website/data-gathering/news-api.ipynb

            - text: Wikipedia 
              file: 5000-website/data-gathering/wikipedia.ipynb

        - text: Data Cleaning
          file: 5000-website/data-cleaning/data_cleaning.ipynb

        - text: Data Exploration
          file: 5000-website/eda/eda.ipynb

        - text: Na√Øve Bayes
          file: 5000-website/naive-bayes/naive_bayes.ipynb

        - text: Dimensionality Reduction
          file: 5000-website/dim-reduction/dim-reduction.ipynb

        - text: Clustering
          file: 5000-website/clustering/clustering.ipynb

        - text: Decision Trees
          file: 5000-website/decision-tree/classification-and-regression.ipynb

        - text: ARM
          file: 5000-website/ARM/arm.ipynb

        - text: Conclusions
          file: 5000-website/conclusions.ipynb

    - title: "Fundamentals"
      contents:
        - fundamentals.qmd
        # navigation items

    - title: "Reference"
      contents:
        - reference.qmd
        # navigation items

    - title: "DSAN 5100"
      contents:
        - text: Introduction
          file: 5100-website/index.ipynb

        - text: Data Collection
          file: 5100-website/air-quality.ipynb

        - text: EDA & Hypothesis Testing
          file: 5100-website/eda/eda.ipynb
    
format:
  html:
    theme: cosmo
    toc: true